### ISSUE TITLE
ModuleNotFoundError: No module named 'pyiron_potentialfit.spgfit'

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron_potentialfit#107]
The module pyiron_potentialfit.spgfit cannot be found.

The input is as following:
```python
from pyiron_potentialfit.spgfit import structures as pstruct
re(pstruct)
```
The error message is as following:
```
--------------------------------------------------------------------
/cmmc/ptmp/pyironhb/mambaforge/envs/pyiron_mpie_cmti_2024-07-01/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from pyiron_potentialfit.spgfit import structures as pstruct
      2 re(pstruct)

ModuleNotFoundError: No module named 'pyiron_potentialfit.spgfit'
------------------------------------------------------------------------------
```

**Comment by pmrv** [comment]
In the new environments from @niklassiemer `pyiron_potentialfit` was still on an older version.  I've updated the version and it should be available again in the environment released next week.  For now you should be able to go back to the `pyiron/old_latest` environment.

**Comment by niklassiemer** [comment]
Thanks

**Comment by niklassiemer** [comment]
@pmrv is there actually a test possible on the docker-stacks to ensure the environment is working?

**Comment by pmrv** [comment]
> @pmrv is there actually a test possible on the docker-stacks to ensure the environment is working?

I don't know, what would I need to check?

**Comment by pmrv** [comment]
@niklassiemer The testing workflow is passing [here](https://github.com/pyiron/docker-stacks/pull/285), is that what you mean?

**Comment by lfzhu-phys** [comment]
@pmrv Thanks a lot.

**Comment by niklassiemer** [comment]
I meant that the old version had been inkompatibel, which I would like to catch :)
