### ISSUE TITLE
Fitsnap: Unknown dependency

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_potentialfit#40]
https://github.com/pyiron/pyiron_potentialfit/blob/1db95608d5ec4ea80c1e99a3beecbe3a77287480/pyiron_potentialfit/fitsnap/common.py#L2

@mgt16-LANL @jan-janssen It seems the fitsnap job class depends on a `pybispectrum` module that I can find neither on PyPI or conda.  Is this code still maintained?

**Comment by jan-janssen** [comment]
That was one of y developments, the function is:
```
def calc_bispectrum_names(twojmax):
    lst = []
    for j1 in range(0, twojmax + 1):
        for j2 in range(0, j1 + 1):
            for j in range(j1 - j2, min(twojmax, j1 + j2) + 1, 2):
                if j >= j1:
                    lst.append([j1 / 2.0, j2 / 2.0, j / 2.0])
    return lst
```
