### ISSUE TITLE
spin configuration in INCAR

### ISSUE THREAD

**Issue by gongyilun** [pyiron/pyiron_potentialfit#80]
Would be nice have element specific initial spin configuration for spgfit structure generation by VASP.

**Comment by pmrv** [comment]
There are still some open issues that prevent running the full workflows with spin polarized DFT.

**Comment by pmrv** [comment]
Latest version fixes those issues. ASSYST can now use collinear DFT settings as shown in the [example](https://github.com/pyiron/pyiron_potentialfit/blob/main/notebooks/assyst/01_Structures.ipynb).
